# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to=b''),
        ),
    ]
