# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20161229_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to=b'store/static'),
        ),
    ]
